[2023-12-13T07:38:50.378+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: countryInfo.get_country_info manual__2023-12-13T07:38:48.750516+00:00 [queued]>
[2023-12-13T07:38:50.395+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: countryInfo.get_country_info manual__2023-12-13T07:38:48.750516+00:00 [queued]>
[2023-12-13T07:38:50.395+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-12-13T07:38:50.395+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-12-13T07:38:50.396+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-12-13T07:38:50.427+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): get_country_info> on 2023-12-13 07:38:48.750516+00:00
[2023-12-13T07:38:50.431+0000] {standard_task_runner.py:55} INFO - Started process 12795 to run task
[2023-12-13T07:38:50.434+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'countryInfo', 'get_country_info', 'manual__2023-12-13T07:38:48.750516+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/CountryInfo.py', '--cfg-path', '/tmp/tmpjeysrdwh']
[2023-12-13T07:38:50.434+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask get_country_info
[2023-12-13T07:38:50.509+0000] {task_command.py:388} INFO - Running <TaskInstance: countryInfo.get_country_info manual__2023-12-13T07:38:48.750516+00:00 [running]> on host 4c47452e42c3
[2023-12-13T07:38:50.599+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=countryInfo
AIRFLOW_CTX_TASK_ID=get_country_info
AIRFLOW_CTX_EXECUTION_DATE=2023-12-13T07:38:48.750516+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-13T07:38:48.750516+00:00
[2023-12-13T07:38:50.600+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/CountryInfo.py", line 23, in get_country_info
    data = request.get(url)
NameError: name 'request' is not defined
[2023-12-13T07:38:50.609+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=countryInfo, task_id=get_country_info, execution_date=20231213T073848, start_date=20231213T073850, end_date=20231213T073850
[2023-12-13T07:38:50.625+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 8 for task get_country_info (name 'request' is not defined; 12795)
[2023-12-13T07:38:50.653+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-12-13T07:38:50.686+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
